### ISSUE TITLE
cannot start the django application up

### ISSUE THREAD

**Issue by ifindthanh** [grindsa/acme2certifier#125]
Hi @grindsa,

I'm not a python developer and getting issue to start the django application under `examples` directory.
There are two issues that I got for now
1. When I run the `python manage.py runserver` command, I always get the following error
```
Exception has occurred: ModuleNotFoundError
No module named 'acme_srv.authorization'
```

Seem like from the django application, it has no connection to the `acme_srv` module
I tried to build the acme_srv module to a tar file and install it locally, but still got no luck.

2. In order to get rid of the first issue, I've to copy all *.py file from the outside `acme_srv` directory to the same directory name but under django directory. With some more modifications, finally I was able to get the server started up.

Now I try to run `python manage.py migrate` command to setting up database schema. This time, I get the following error
```
starting acme2certifier version 0.29.2
acme2certifier database version mismatch in: version is None but should be 0.29.2. Please run the "tools/django_update.py" script
Operations to perform:
  Apply all migrations: acme_srv, admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0002_remove_content_type_name...Traceback (most recent call last):
  File "C:\xxxxxxxx\acme2certifier\examples\django\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\core\management\base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\core\management\base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\core\management\commands\migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\db\migrations\executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\db\migrations\executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\db\migrations\executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    with atomic(schema_editor.connection.alias):
  File "C:\Users\T480\anaconda3\Lib\site-packages\django\db\transaction.py", line 227, in __exit__
    connection.atomic_blocks.pop()
IndexError: pop from empty list
```

I don't see any instruction for starting up this application. So what should I do to achieve that?

**Comment by ifindthanh** [comment]
yes, it is a new installation

**Comment by grindsa** [comment]
Hi, 

i am sorry for letting you waiting but i was busy with other tasks. Here are the commands to setup a local django based a2c instance using sqllite as backend database....

Let me know if this works for you. I am planning to create some official documentation in the upcoming days...

1. download and unpack the archive
2. enter the acme2certifier directory

```bash
cd acme2certifier-0.30/
```
3. install django3 (django4 is not supported yet) and misisng python packages
```bash
pip3 install django==3.2.23
pip3 install -r requirements.txt
```

4. copy django files into the source directory
```bash
cp -R examples/django/* ./
cp examples/db_handler/django_handler.py acme_srv/db_handler.py 
```

5. generate a new django-scret key and capture the new key

```bash
python3 tools/django_secret_keygen.py
```
`
6. open `acme2certifier/settings.py`

7. add the key generated in step 5 to the `SECRET_KEY` variable

```bash
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'eixb4779sd3_+*9voff_f^hy7p=6@ml0r4mt)f#^(m9p@$&v$^'
```

8 modify the `[DATABASE]` section of the `settings.py` file as below

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS': {'timeout': 20}
    }
}
```

9. create migration set and apply migration
```
python3 manage.py  makemigrations
python3 manage.py  migrate
```

10. configure acme2ceritifer especially the CAhandler according to your needs

11. start the development server
```
python3 manage.py runserver 0.0.0.0:80
```

**Comment by ifindthanh** [comment]
thank you @grindsa , I followed the instruction and were able to start the server up with sqlite database.
I also tried with MySQL but getting this error when running `python3 manage.py  migrate`
```
Operations to perform:
  Apply all migrations: acme_srv, admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0002_remove_content_type_name...Traceback (most recent call last):
..................................................................................................................................................................................................................
django.db.utils.OperationalError: (1054, "Unknown column 'name' in 'django_content_type'")
```

**Comment by grindsa** [comment]
Can you please post the content of the `DATABASES` variable of your `settings.ini`?
Did you create an empty database on your mysql server as the corresponding user having proper access rights?

**Comment by ifindthanh** [comment]
ah my bad, the database is not empty when I do the migration.
I drop and re-create it before running migration again, it works for now.

Thank you very much!

**Comment by ifindthanh** [comment]
Trying to use lego for testing acme requests and getting this error at first command
```
acme2certifier database error in Order._add() order: Status matching query does not exist.
```
I believe that the error is related to foreign key setting of `acme_srv_order` table to `acme_srv_status` table. 
Adding Order record with a specified Status will create this error.
I think a step to migrate data of `acme_srv_status` is missed from this instruction.
Or anything else that I missed?

**Comment by grindsa** [comment]
my bad. I indeed forgot to add one comment which is prefilling the `status` table.

```
python3 manage.py loaddata acme_srv/fixture/status.yaml
````

**Comment by grindsa** [comment]
closing due to inactivity
