### ISSUE TITLE
Wrong attribute name in JSON error response

### ISSUE THREAD

**Issue by RicMin** [grindsa/acme2certifier#92]
Hello, using the Acme4J client library I found that the "type" attribute that should be present in the error JSON structure has the name "message" instead. This seems to me to be a non-compliance with the RFC. For verification I did the same check with the "Let's encrypt" server and I saw that my client works correctly.
Below is the extract of my application log in which the problem is highlighted.

2022-05-19 17:59:08,706 [main] DEBUG: finalize
2022-05-19 17:59:08,713 [main] DEBUG: POST http://hostname/acme/order/N6ZNKCrcCJ4X/finalize
2022-05-19 17:59:08,713 [main] DEBUG:   Payload: {"csr":"MIICnzCCAYcCAQAwMDEVMBMGA1UEAwwMd3d3LnRlc3QuY29tMRcwFQYDVQQKDA5BY3RhbGlzIFMucC5BLjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALlIM6kLGlRc4GXbru8DAbdSZLU26tuUdZUwO2rVL8Szo4cvt9v6Dtt42byMlHQG9A4YHV6JFtaZQXx4zksrNRuPkV999XSNWxQ_xvoU6rKBtFWzIuXIX8mbS3y4Vbh1fOPTRM32UFdlM4r4qbco3vnBVT0vlVpIoqj30Wlwv8_BkWJ3T0X8oNMeYWThhaF-bEN6H8gCz_ep1rW81FUc_--scgVNVtLdI6UbPnblbremNiNhY4DylFXmto7L80nhP3U_dj3WjvqPJGvc1H5WRlBs3WFDjCIB3mHYV7uuOKS0lIvZGaWQ_EzlNmCfsteqeCWFzQ6B6P2rgn2Z-9jSPEECAwEAAaAqMCgGCSqGSIb3DQEJDjEbMBkwFwYDVR0RBBAwDoIMd3d3LnRlc3QuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQCLKlWn4agXyeJHRydUv_K4yDtUmew5FkCjzwpRmjLwtma3_lC4OdYc1Uz7xGozmdlgld01CeXj4vjITnIwU2BKSYo9gXlKIWajeVxMyqDcGBen-NX5MNP9Y0OSJ_v_tqCTqrc0PAQjHRUyIo3v6VrRhSYJ-lmUpnH0cTWNm30NkyZ7r0QfSLI2csxFp1nf8f-maWypf2I7FYEVs03BXWHIkwVx3SIUhefCYGrXZBiF51_3aV0nXyfD012IGSnYQosOUyycZi5-llfW8-WYnvVLVjhSjzEPDW_UEe-x-uxu0QKC7LR7aM1_kAUdNIRR2VvUx9vxLAcsC9ZiVAufBak9"}
2022-05-19 17:59:08,715 [main] DEBUG:   JWS Header: {"url":"http://hostname/acme/order/N6ZNKCrcCJ4X/finalize","kid":"http://devk8s.actalis.it/acme/acct/V8EzIeuHgdGC","nonce":"60955f4b07cd4e04a89e224c77654b18","alg":"RS256"}
2022-05-19 17:59:08,767 [main] DEBUG: HEADER Transfer-Encoding: chunked
2022-05-19 17:59:08,768 [main] DEBUG: HEADER null: HTTP/1.1 403 Forbidden
2022-05-19 17:59:08,768 [main] DEBUG: HEADER Server: nginx/1.21.3
2022-05-19 17:59:08,768 [main] DEBUG: HEADER Connection: keep-alive
2022-05-19 17:59:08,768 [main] DEBUG: HEADER Date: Thu, 19 May 2022 15:59:25 GMT
2022-05-19 17:59:08,768 [main] DEBUG: HEADER Content-Type: application/problem+json
2022-05-19 17:59:08,771 [main] DEBUG: Result JSON: {"status":403,"**message**":"urn:ietf:params:acme:error:orderNotReady","detail":"Order is not ready"}
Exception in thread "main" org.shredzone.acme4j.exception.AcmeProtocolException: **Problem without type**
	at org.shredzone.acme4j.Problem.lambda$getType$1(Problem.java:67)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.shredzone.acme4j.Problem.getType(Problem.java:67)
	at org.shredzone.acme4j.connector.DefaultConnection.throwAcmeException(DefaultConnection.java:528)
	at org.shredzone.acme4j.connector.DefaultConnection.performRequest(DefaultConnection.java:479)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:407)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:161)
	at org.shredzone.acme4j.Order.execute(Order.java:166)
	at it.apps.pki.Application.main(Application.java:276)

**Comment by grindsa** [comment]
I understand the problem and will work in a fix Is there any chance to share an acme-client based on Acme4J  which i can use for regression testing?

**Comment by grindsa** [comment]
Hi, I created a [separate branch](https://github.com/grindsa/acme2certifier/tree/type_field) containing a few changes which should address your problem. I also created a [special container](https://hub.docker.com/layers/acme2certifier/grindsa/acme2certifier/type_field/images/sha256-f15ae79ef746a3ca5f2940f8ee4a292053511136a50229e06be7c13f870b02bf?context=explore) which can be downloaded via `docker pull grindsa/acme2certifier:type_field`. Can you please check if the changes address your problem? I am unfortunately missing a client to do so.

**Comment by grindsa** [comment]
ok i will push the changes to `master` branch and will release a new version by tomorrow latest. Again, any recommendation for a client implementation that I can put this into my regression testing?

**Comment by grindsa** [comment]
Fix made it finally into [v0.22](https://github.com/grindsa/acme2certifier/releases/tag/0.22). Sorry for the delay...
